services:
  backend:
    build:
      context: ./backend
    container_name: stocks_backend
    ports:
      - 4047:4001

  frontend:
    build:
      context: ./frontend
    container_name: stocks_frontend
    ports:
      - 4046:3111
